[project]
name = "clearml-exp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "black>=25.1.0",
    "clearml>=1.18.0",
    "fiftyone>=1.5.2",
    "ipython>=8.36.0",
    "isort>=6.0.1",
    "ruff>=0.11.9",
]

